### PR TITLE
Allow selecting backends by setting a environment variable

### PR DESCRIPTION
**Pull request by herm**
I implemented part of the idea from bug #194.

### CODE REVIEW

**Comment by herm** [comment]
This pull request was opened two years ago. Is there any problem with the code or what else can I do to get it merged?

**Comment by MatthieuDartiailh** [comment]
Sorry @hgrecco is not very responsive and I had no time to look at this PR. I will try to do so before next week and merge if everything is fine.

Thanks for the ping !

**Comment by MatthieuDartiailh** [comment]
This looks good. I will try to test before merging but I would like to see this in the documentation (probably in this file https://github.com/pyvisa/pyvisa/blob/master/docs/configuring.rst)

**Comment by MatthieuDartiailh** [comment]
Just waiting for the documentation update to merge.

**Comment by herm** [comment]
Documentation added.

**Comment by MatthieuDartiailh** [comment]
Thanks @herm 

bors r+

**Pull request merged**
