### PR TITLE
fix: Apply language edits for clarity and tense

### PR DESCRIPTION
**Pull request by matthewfeickert**
This PR applies general language edits for grammar, clarity, and tense for the JOSS paper submission in https://github.com/openjournals/joss-reviews/issues/5304.

These edits reflect my understanding as a reader, but if there are strong disagreements with them they very much can be revised &mdash; these are not editorial edicts. :+1:

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@hgrecco this is ready for review. I'm happy to discuss anything if you have questions.

**Review by MatthieuDartiailh — APPROVED** [review]
As I co-author I am fine with those changes

**Comment by matthewfeickert** [comment]
@hgrecco @MatthieuDartiailh If you're happy with these edits then once these are merged in then we can move forward with the publishing steps in https://github.com/openjournals/joss-reviews/issues/5304.

**Comment by matthewfeickert** [comment]
:wave: @hgrecco Just wanted to ping on this to see if you had time to review it so we can move to the next steps of the publication process for https://github.com/openjournals/joss-reviews/issues/5304.

**Comment by hgrecco** [comment]
Sorry for the long delay.

**Pull request merged**
