### PR TITLE
Gpib commands

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
- [x] Executed ``black . && isort -c . && flake8`` with no errors
- [ ] Documented in docs/ as appropriate
- [ ] Added an entry to the CHANGES file

Add a more convenient interface for accessing GPIB commands and improve grou_execute_trigger.

@greyltc if you can test this it would be amazing.

### CODE REVIEW

**Comment by LongnoseRob** [comment]
> @LongnoseRob @tivek if you get a chance to test things over this GPIB, this PR could use some testing. I do not have access to GPIB at the moment but I hope to solve this issue over the summer.

@MatthieuDartiailh, 
Its been a while on this topic, but as I now have an Instrument on which I would like to try to get SRQ-based events a try, I am back on this topic now.

I just gave this PR a quick try with my HPAK 82357B USB-GPIB Adapter and the trusty old HP3478A multimeter.
Checked out this PR and also pyvisa-py:#276 and wrote a short test script
[20211208_HP3478A_pr552_test.txt](https://github.com/pyvisa/pyvisa/files/7676488/20211208_HP3478A_pr552_test.txt)

It does not go horribkle wrong, but something is still not working right, as I always get the same status infomation

```
robby@octoberrain pyvisa]$ python 20211208_HP3478A_pr552_test.py
libgpib: invalid descriptor
[ same lines omitted for brevity]
libgpib: invalid descriptor
('ASRL/dev/ttyS4::INSTR', 'ASRL/dev/ttyS0::INSTR', 'GPIB0::23::INSTR')
+2.57800E+0 [a simple read to have some data flowing over the bus]
InterfaceType.gpib
+2.56700E+0
LLO:  (None, <StatusCode.success: 0>)
+2.56800E+0
GTL:  (None, <StatusCode.success: 0>)
+2.59700E+0
SDC:  (None, <StatusCode.success: 0>)
+2.59700E+0
PPC:  (None, <StatusCode.success: 0>)
+2.59700E+0
PPU:  (None, <StatusCode.success: 0>)
GET:  (None, <StatusCode.success: 0>)
+2.59500E+0
TCT:  (None, <StatusCode.success: 0>)
+2.59000E+0
DCL:  (None, <StatusCode.success: 0>)
+2.58500E+0
SPE:  (None, <StatusCode.success: 0>)
+2.57800E+0
SPD:  (None, <StatusCode.success: 0>)
+2.57100E+0
CFEE:  (None, <StatusCode.success: 0>)
+2.56600E+0
UNT:  (None, <StatusCode.success: 0>)
+2.56600E+0
UNL:  (None, <StatusCode.success: 0>)

```
Could you please have a look at the attached test-script?
Am I doing something wrong here?
Am I not using the correct syntaxt for sending a command?

**Comment by MatthieuDartiailh** [comment]
I will have a look but it may take some time. I became a dad last Sunday so my time is very limited.

**Comment by LongnoseRob** [comment]
> I will have a look but it may take some time. I became a dad last Sunday so my time is very limited.
Congratulations!
Don't worry, take care of the new earthlingm.
I will give it some more tries and see what I can find out.

**Comment by MatthieuDartiailh** [comment]
Partially from memory, send_command expect bytes. The idea is to use the GPIBCommand enum to get readable code so something like `ifc.send_command(GPIBCommand.GTL)`

**Comment by LongnoseRob** [comment]
> Partially from memory, send_command expect bytes. The idea is to use the GPIBCommand enum to get readable code so something like `ifc.send_command(GPIBCommand.GTL)`

if I try as you proposed I get a NameError:

```
my_ifc.send_command(GPIBCommand.GTL)
Traceback (most recent call last):

  File "/tmp/ipykernel_7956/2804746168.py", line 1, in <module>
    my_ifc.send_command(GPIBCommand.GTL)

NameError: name 'GPIBCommand' is not defined
```
but the `GPIBCOmmand`-class is defined in pyvisa/ressources/gpib.py,
so I would expect it to be avialble if have the normal `import pyvisa` at the beginning of my script.

**Comment by MatthieuDartiailh** [comment]
Honestly I do bot remember if I bubbled GPIBCommand all the way to the package root But even If I did if you simply import pyvisa you would need pyvisa.GPIBCommand.

**Comment by LongnoseRob** [comment]
Ok figured it out, it was a mistake on the user level..
(had the PR cloned correctly, but had forgotton to run `python setup,py develop`, so pyhon was not using the right pyvisa files.)

Now I can use `pyvisa.resources.gpib.GPIBCommand.LLO`  in `my_ifc.send_command(pyvisa.resources.gpib.GPIBCommand.LLO))`
Which causes all devices on my GPIB setup to go to LLO mode --> sucess.

However if I now try to issue a GTL, nothing happens, I think because we need to adress the deice first..

**Comment by MatthieuDartiailh** [comment]
Yes as documented on line 28 GTL only affect addressed devices.

**Comment by dirkjankrijnders** [comment]
Hi, I did some more testing of GPIB commands.

Setup: 

- PyVISA-py: branch `gpib-commands`, rebased on main
- PyVISA: branch `gpib-commands`, rebased on main
- linux-gpib: 4.3.6 with debug enabled

First I tested the same command as LongnoseRob above:
```
my_ifc.send_command(GPIBCommand.SDC)
(None, <StatusCode.success: 0>)
```
However this did nothing to the device. Using `ibtest` and sending `SDC` using the `send (d)evice clear (device only)` device did reset the device as expected. So I looked into the kernel messages and the difference was clear:
Output for python:
```
[ 3480.255420] gpib_bitbang:bb_write - board 00000000a59b55ad  lock 1  length: 1
[ 3480.255425] gpib_bitbang:bb_buffer_print - <cmd len 1>
[ 3480.255430] gpib_bitbang:bb_buffer_print - 0x4=SDC
[ 3480.255435] gpib_bitbang:bb_write - Enabling interrupts - NRFD: 1   NDAC: 0
[ 3480.256962] gpib_bitbang:bb_write - sent 1 bytes
```
Output for ibtest:
```
[ 3387.601449] gpib_bitbang:bb_write - board 00000000a59b55ad  lock 1  length: 4
[ 3387.601464] gpib_bitbang:bb_buffer_print - <cmd len 4>
[ 3387.601475] gpib_bitbang:bb_buffer_print - 0x40=TLK0
[ 3387.601488] gpib_bitbang:bb_buffer_print - 0x3f=LSN31
[ 3387.601500] gpib_bitbang:bb_buffer_print - 0x35=LSN21
[ 3387.601512] gpib_bitbang:bb_buffer_print - 0x4=SDC
[ 3387.601525] gpib_bitbang:bb_write - Enabling interrupts - NRFD: 1   NDAC: 0
[ 3387.611505] gpib_bitbang:bb_write - sent 4 bytes
```

So the PyVISA does not address to device first. Which makes senses a the command is done on the interface and not the instrument. Question now is how to send this command to the device.

**Comment by dirkjankrijnders** [comment]
Another small thing: notice how `ibtest` sends a 0x35=LSN21. This would be the equivalent of `GPIBCommand.MLA`. But `20 + device_pad` in line 101, with device_pad = 21, does not give `0x35`. The line should be `0x20 + device_pad`. Something similar happens in line 96.

**Comment by dirkjankrijnders** [comment]
Getting more at home with the code, I think adding commands that work on a device should be implemented as `selected_device_clear` (SDC) is now: as a member function of `GPIBSession`. I suggest to add `go_to_local()` (`GTL`), `local_lockout()` (`LLO`), `untalk()` (`UNT`), `unlisten()` (`UNL`), `serial_poll_enable()` (`SPE`)  and `serial_poll_disable()` (`SPD`). Parallel polling is not implemented in the driver I use... `DCL` should be implemented in the `GPIBInterface` then.

**Comment by MatthieuDartiailh** [comment]
I rebased this on latest main.

The goal of this PR is to provide a reasonably clean access to GPIB commands, it was not my intention to expand significantly over the  API surface already exposed. ``group_execute_trigger`` exists because it is a common GPIB pattern and providing a helper was deemed useful at one point.

I am not opposed to adding additional helpers but I would like to see some motivations beyond the fact that we can.

**Comment by dirkjankrijnders** [comment]
Hi, I realised it was a long list after I posted. Maybe a convenience function `send_command` on `GBIPSession` so you can do `my_inst.gpib_command(GPIBCommand.GTL)`. A similar function exists on `GBIPInterface`, but this would first address the instrument first. 

I have rerun my tests with code from the latest rebase and can report it works.

**Comment by MatthieuDartiailh** [comment]
Thanks @dirkjankrijnders 

I was distracted by other topics but I will take care of this PR next week. I think I will merge as is and we can consider adding helper method on GPIBInstrument in a follow up PR. Once it is merged, I will update the pyvisa-py PR to use it and may ask you to test again if that is OK.

**Pull request merged**
