### PR TITLE
Message based improvements

### LINKED ISSUE #252: 'Can't concat bytes to str' error when calling write_ascii_values
It's very strange, as message.encode(enco) is bytes and util.to_ascii_block() returns string, so line 239 of messagebased.py `message = message.encode(enco) + block` fails with an error specified in the title. 
I use "d" for converter and "," for separator
Why is this happening, wasn't it tested at all or am I doing something wrong?

I could fix it trivially by calling .encode on the block variable.

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
~~This is WIP and untested so far~~ This has now been fully tested locally:
- implement HP binary header following @thliebig work ~~(I plan on adding tests)~~ done
- fix the issue in write_ascii_values by properly encoding the values in `utils.to_ascii_block` (closes #252)
- add noisy warnings to encourage migrations to new api for values reading/writing
- uniformize the API for reading values by providing read_ascii_values and read_binary_values

Also make all file concerned by the update be PEP8 compliant.

I hope to complete and test this before Christmas, but anybody is welcome to test and review.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
The broken tests come from Python 2.6. As we are likely to drop support for it in January I will not try to fix it. This is ready for review from my end. ping @hgrecco, @skrchnavy

**Comment by thliebig** [comment]
@MatthieuDartiailh, I have added a missing fixup for the improved header support:
https://github.com/thliebig/pyvisa/commit/f9879997ef87f6d903be63bb90ab9efa5d74a43e
It catches the case that a termination character happens to be the last valid data byte(s). It occurs only very very rarly, but it does and it then crashes the read... Please consider adding the path to this PR

**Comment by MatthieuDartiailh** [comment]
Done. And I set you as author. This somehow always bothered me but as it worked in my tests as I forgot to spend more time on it. If you can do a complete review it would be awesome.

**Comment by MatthieuDartiailh** [comment]
@thliebig Do you want to do a final review before I merge ?

**Comment by MatthieuDartiailh** [comment]
Merging.

bors r+

**Comment by rjollos** [comment]
`MessageBasedResource.values_format` is deprecated according to the warning issued when setting the attribute, but it is still documented in the section [Preconfiguring the transfer format](https://pyvisa.readthedocs.io/en/master/rvalues.html?highlight=values_format#preconfiguring-the-transfer-format).

Is there an alternate recommendation? Before discovering the attribute I was using a partial function to avoid specifying the attributes for every query:

```python
query = functools.partial(inst.query_ascii_values, separator=',', container=numpy.array)
```

**Comment by MatthieuDartiailh** [comment]
This exact issue is being discussed in https://github.com/pyvisa/pyvisa/issues/327. The short answer is currently there is no way to preconfigure the parameters.

The docs definitively needs to be re-worked and indeed that mention should be removed. 

I am short of time currently so if you feel like to address any of these issues I will be happy to review PR.

**Comment by rjollos** [comment]
> I am short of time currently so if you feel like to address any of these issues I will be happy to review PR.

Thanks for the reply. I would like to understand the pyvisa architecture and make some contributions, so I will try to prepare a pull request in the near future.

**Pull request merged**
