### PR TITLE
Fix rendering of code

### PR DESCRIPTION
**Pull request by jpsecher**
This is only a space inserted in the documentation to make it render properly.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Let me know when this is good to go.

**Comment by jpsecher** [comment]
OK, I think that was it for now.  Ready for a squash.

**Comment by MatthieuDartiailh** [comment]
Thanks ! I will try to figure out why CIs did not run before merging. Likely next weekend.

**Comment by jpsecher** [comment]
Well, I got tired of trying to get the GitHub web interface to do what I wanted, so I manually pushed to the branch on my fork.  That might be why CI did not kick in.

**Comment by MatthieuDartiailh** [comment]
I don't have time to look at the CI now but I do not want to hold you contribution so 

bors r+

Thanks again for your help.

**Comment by MatthieuDartiailh** [comment]
The Keysight bot is down but it does not matter for this PR.

**Pull request merged**
