### PR TITLE
#280: Add VISA Resource Regular Expression syntax description in list…

### PR DESCRIPTION
**Pull request by awneil**
…_resources(),

and list_resources_info()

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
This looks great ! Thanks for putting it together !

Could also add a quick note (not the full explanation) to https://github.com/pyvisa/pyvisa/blob/master/docs/tutorial.rst ? In particular insisting on the fact that the default query does not return anything else than INSTR (so no RAW or SOCKET which is a usual question). If you can't, let me know and I will do it once I merged this.

**Comment by awneil** [comment]
Sorry it took so long!

Could you point me to a reference for the formatting in a .rst file ?

**Comment by MatthieuDartiailh** [comment]
I found some time to work on the docs. I will merge as is and open a PR for the docs update after. Thanks for your time @awneil.

bors r+

**Comment by awneil** [comment]
ah - I hadn't added the note in the .RST.

So should I now make a new branch to do that?

**Comment by MatthieuDartiailh** [comment]
Do not worry I added the note in #323 which is waiting for a small test on my end before it gets merged.

**Comment by awneil** [comment]
ok - thanks.

:+1:

**Pull request merged**
