### PR TITLE
shell: support for 'termchar' command

### PR DESCRIPTION
**Pull request by skrchnavy**
Added support for termination character (read_termination) setup / read into shell (visa command line tool).

To display termination character
```
(open) termchar
```
To set termination character (read and write)
```
(open) termchar <termchar> [<termchar>]
```
`<termchar>` is one of `CR`, `LF`, `CRLF`, `NUL`.
To disable termination character, `None` shall be used
If two termchars are provided, first is read termination character and second is write termination character

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Here you only change the read_termchar and from experience both are useful (and sometimes the write even more than the read). SO If you want to add an easier access to those I would suggest adding both and also potentially supporting other characters if possible (I remember an instrument using '\0' as termchar).

**Comment by skrchnavy** [comment]
My main intention was to simplify setting of termchar and termchar_en using one command, because termchar_en is False by default. (and also setting termchar for ni driver doesn't work for me, wrong type).
Setting write is possible, but I ma not sure if it shall be setup in common command or 2 different commands. If common set is OK as typical cas, I am OK with such change.
Other characters as termchar is possible via `attr` command, anyway if '\0' is used, it shall be added.

**Comment by skrchnavy** [comment]
@MatthieuDartiailh 
I have updated implementation and also description of this PR with support for read and write termination. Also NUL is supported.

**Comment by MatthieuDartiailh** [comment]
I made a minor modification in the docs but this looks good. Merging

bors r+

**Comment by MatthieuDartiailh** [comment]
One minor thing I forgot before merging, to check that a key exist inside a dictionary the following syntax is more often used (compared to has_key):
```python
if key in mydict:
    pass
```

**Pull request merged**
