### PR TITLE
Add `chunk_size` and `data_length` to `read/query_binary_values`

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This address a couple of issues and is based on #430 :
- `chunk_size` appears to be able to fix the issue seen in #431, even if at the time being the underlying issue is not clear but is likely outside of PyVISA (whether it is a VISA implementation issue or an instrument specific is unclear)
- `data_length` fills a gap by providing a way to get in a controlled manner binary data from instrument that use a protocol that do not report how many bytes will be transferred (such as the Keithley 2000 which is commonly used with PyVISA). **I still have some work to do on the utility functions to handle this properly**

The documentation has been updated to reflect those changes.  The changelog must be updated before merging. @bjaraujo if you can test and review, I would greatly appreciate it.

### CODE REVIEW

**Comment by bjaraujo** [comment]
This works correctly so I think you can merge this in. 
It behaves the same as expected without specifying chunk_size. In cases it does fail, allowing a bigger chunk_size, fixes the issue so I am happy.

So I have tested large binary transfers for GPIB, USBTMC and HiSLIP. 

With default chunk_size it crashes sometimes:
image

or it says this:

Traceback (most recent call last):
  File "test.py", line 31, in <module>
    values = inst.query_binary_values('DATA?', datatype='d')
  File "...\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvisa\resources\messagebased.py", line 701, in query_binary_values
    data_length, chunk_size)
  File "...\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvisa\resources\messagebased.py", line 478, in read_binary_values
    block = self._read_raw(chunk_size)
  File "...\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvisa\resources\messagebased.py", line 386, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "...\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1584, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "...\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
    raise errors.VisaIOError(ret_value)
pyvisa.errors.VisaIOError: VI_ERROR_INV_SETUP (-1073807302): Unable to start operation because setup is invalid (usually due to attributes being set to an inconsistent state).

By increasing chunk_size like so:
values = inst.query_binary_values('DATA?', datatype='d', chunk_size=2000*1024)
this issue goes away.

Although it might be a VISA problem, specifying chunk_size allows the user to get around it.

**Comment by bjaraujo** [comment]
@MatthieuDartiailh Is this going to be merged in?

**Comment by MatthieuDartiailh** [comment]
I need to polish a couple of things for the specific case of a non-reported length in ieee format. I should be able to do so and test Monday. I also plan a release before the end of July that will include this feature.

**Comment by MatthieuDartiailh** [comment]
I will also add the additional error messages you mentioned to the docs since they are quite cryptic.

**Comment by bjaraujo** [comment]
Thanks. Sounds good.

**Comment by MatthieuDartiailh** [comment]
I add to make a couple additional changes. I will test again tomorrow and merge if everything is fine.

**Comment by MatthieuDartiailh** [comment]
Everything looks fine on my side. Could you quickly review and test @bjaraujo ?

**Comment by bjaraujo** [comment]
Unfortunately I can't atm. I might be able to do that next week.

**Comment by MatthieuDartiailh** [comment]
@bjaraujo did you get a chance to test ?

**Comment by bjaraujo** [comment]
Sorry. Very busy atm. Will give a try next week.

**Comment by bjaraujo** [comment]
@MatthieuDartiailh 

Tested and works fine.

**Comment by MatthieuDartiailh** [comment]
Thanks ! I will do my best to release tonight.

**Pull request merged**
