### PR TITLE
Add citing information to README and GitHub Citation

### PR DESCRIPTION
**Pull request by hgrecco**
Following the publication of the PyVISA paper in JOSS, this PR add the citation information to the README and GitHub repository:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Why do you also add the paper to the repository root ?

**Comment by hgrecco** [comment]
Putting paper.md and paper.bib in the root was part of submitting this to JOSS (I guess there was another way but not clear for me). This can be moved now.

**Comment by MatthieuDartiailh** [comment]
I would prefer to see it moved. Under a joss-paper directory, maybe.

**Comment by hgrecco** [comment]
Done!

**Pull request merged**
