### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This is a HUGE pull request. That was not my intention at first but everything ended up this way and there is no clean way to sub divide it. Here is a list of what this PR addresses:

- Code quality changes:

    - use black to format the whole codebase (the initial change is in a single commit allowing to filter it if necessary)
     - use isort to format imports
     - use flake8 to lint the code
    - add type annotations and use mypy to type check the code
    - configure CIs to validate that all the above is done consistently
    - add pre-config to ease the use of those tools for developer
    - use Numpy style doctrsing for all docstrings

- Usability changes:

    - declare VISA attributes on resources rather than magically monkeypatch, should greatly improve the discoverability of those (in particular for serial resources this is important)
    - use more enums to clarify valid inputs for a number of low level functions
    - introduce event classes to wrap event. This provides a nicer interface to access events attributes
    - BREAKING CHANGE: wrap handlers to avoid passing raw ctypes values back (except for user_handle where this cannot be avoided). This is on by default but can be disabled using an environment variable or a global variable.
    - provide a `wrap_handler` method on resources allowing to get directly a resource and event object rather than low-level VISA object.
    - document the way to use events in pyvisa using either the queue mechanism or the handler mechanism.

This is a very large change set but given the number of static analysis tools now running and the fact that when run using the Keysight testing tools the coverage now reaches 93% we should avoid breakages. However I would be happy to see people testing this before I merge. Pinging @hognala, @KOLANICH, @hgrecco 

@jenshnielsen I know that QCoDeS uses mypy and I would be happy to know if this helps or if I got part of the typing wrong.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
NOTE: the API documentation could still use a rework

**Comment by bilderbuchi** [comment]
Wow! I have no way to test this meaningfully, but I am wondering about one thing: for [converting the docstrings to numpy format](c7699750e6d7e71af635963aa757ec343f4c9dd6), is there an automated tool to do that, or was that manual work + looking at pydocstyle output?

**Comment by MatthieuDartiailh** [comment]
Manual, but doing the typing helped.

**Comment by MatthieuDartiailh** [comment]
By the way any kind of test you can do @bilderbuchi is welcome. Apart from the handler change nothing else should cause any kind of trouble. I am conscious that it is a disruptive change but going forward will be easier after it is done.

**Comment by MatthieuDartiailh** [comment]
To make clear what is covered I also uploaded the report from the setup I have running with the Keysight virtual instrument. Hopefully Codecov won't be too confused.

**Comment by bilderbuchi** [comment]
I'll try, but nearly all my sparetime coding time (which is nearly none nowadays) is consumed with trying to help push pymeasure onwards. :-/

**Comment by jenshnielsen** [comment]
To make the types available for any thirdparty package you will need to add a py.typed file to the distribution https://www.python.org/dev/peps/pep-0561/#id18

As it stands I cannot install from this branch

```
 ERROR: Command errored out with exit status 1:
   command: 'C:\Users\jenielse\AppData\Local\Continuum\miniconda3\envs\qcodes\python.exe' 'C:\Users\jenielse\AppData\Local\Continuum\miniconda3\envs\qcodes\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\jenielse\AppData\Local\Temp\tmp_ezepifm'
       cwd: C:\Users\jenielse\AppData\Local\Temp\pip-req-build-7w3zcaxj
  Complete output (62 lines):
  Traceback (most recent call last):
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 90, in __init__
      req = REQUIREMENT.parseString(requirement_string)
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1654, in parseString
      raise exc
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1644, in parseString
      loc, tokens = self._parse( instring, 0 )
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache
      loc,tokens = self.parseImpl( instring, preloc, doActions )
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3417, in parseImpl
      loc, exprtokens = e._parse( instring, loc, doActions )
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache
      loc,tokens = self.parseImpl( instring, preloc, doActions )
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3739, in parseImpl
      return self.expr._parse( instring, loc, doActions, callPreParse=False )
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache
      loc,tokens = self.parseImpl( instring, preloc, doActions )
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3400, in parseImpl
      loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1406, in _parseNoCache
      loc,tokens = self.parseImpl( instring, preloc, doActions )
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 2711, in parseImpl
      raise ParseException(instring, loc, self.errmsg, self)
  pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\__init__.py", line 3111, in __init__
      super(Requirement, self).__init__(requirement_string)
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 94, in __init__
      requirement_string[e.loc:e.loc + 8]))
  pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at ""['setupt""

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\jenielse\AppData\Local\Continuum\miniconda3\envs\qcodes\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
      main()
    File "C:\Users\jenielse\AppData\Local\Continuum\miniconda3\envs\qcodes\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\jenielse\AppData\Local\Continuum\miniconda3\envs\qcodes\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\setuptools\build_meta.py", line 148, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\setuptools\build_meta.py", line 128, in _get_build_requires
      self.run_setup()
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 7, in <module>
      setup(use_scm_version=True)
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\setuptools\__init__.py", line 143, in setup
      _install_setup_requires(attrs)
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\setuptools\build_meta.py", line 59, in fetch_build_eggs
      specifier_list = list(map(str, parse_requirements(specifiers)))
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\__init__.py", line 3104, in parse_requirements
      yield Requirement(line)
    File "C:\Users\jenielse\AppData\Local\Temp\pip-build-env-vul6a357\overlay\Lib\site-packages\pkg_resources\__init__.py", line 3113, in __init__
      raise RequirementParseError(str(e))
  pkg_resources.RequirementParseError: Invalid requirement, parse error at ""['setupt""
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\jenielse\AppData\Local\Continuum\miniconda3\envs\qcodes\python.exe' 'C:\Users\jenielse\AppData\Local\Continuum\miniconda3\envs\qcodes\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\jenielse\AppData\Local\Temp\tmp_ezepifm' Check the logs for full command output.
```

**Comment by MatthieuDartiailh** [comment]
Thanks for the pointer @jenshnielsen . I added the required file and fixed the setup.cfg issues. I will fix the small mypy issue later.

**Comment by MatthieuDartiailh** [comment]
I also re-uploaded the coverage using Keysight tools.

**Comment by bilderbuchi** [comment]
I am intrigued by this remark - what Keysight tools are you using? to do what? and where is this coverage report being uploaded? 
I dug around in the workflow actions, but I only found the pytest coverage upload to codecov, no Keysight things...

**Comment by jenshnielsen** [comment]
I am seeing the following traceback when I try running mypy (0.770) against qcodes master and this branch at 05fa683 Not really sure why that is and I unfortunatly don't have the time to look at it right now.

```
Traceback (most recent call last):
  File "c:\users\jens-work\miniconda3\envs\qcodes\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jens-work\miniconda3\envs\qcodes\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jens-Work\Miniconda3\envs\qcodes\Scripts\mypy.exe\__main__.py", line 7, in <module>
  File "c:\users\jens-work\miniconda3\envs\qcodes\lib\site-packages\mypy\__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy\main.py", line 89, in main
  File "mypy\build.py", line 180, in build
  File "mypy\build.py", line 249, in _build
  File "mypy\build.py", line 2649, in dispatch
  File "mypy\build.py", line 2949, in process_graph
  File "mypy\build.py", line 3027, in process_fresh_modules
  File "mypy\build.py", line 1954, in fix_cross_refs
  File "mypy\fixup.py", line 25, in fixup_module
  File "mypy\fixup.py", line 89, in visit_symbol_table
  File "mypy\fixup.py", line 45, in visit_type_info
  File "mypy\fixup.py", line 91, in visit_symbol_table
  File "mypy\nodes.py", line 766, in accept
  File "mypy\fixup.py", line 117, in visit_decorator
  File "mypy\nodes.py", line 874, in accept
  File "mypy\fixup.py", line 136, in visit_var
  File "mypy\types.py", line 1098, in accept
  File "mypy\fixup.py", line 182, in visit_callable_type
  File "mypy\types.py", line 1857, in accept
  File "mypy\fixup.py", line 257, in visit_type_type
  File "mypy\types.py", line 1347, in accept
  File "mypy\fixup.py", line 219, in visit_tuple_type
  File "mypy\types.py", line 794, in accept
  File "mypy\fixup.py", line 158, in visit_instance
  File "mypy\types.py", line 794, in accept
  File "mypy\fixup.py", line 153, in visit_instance
  File "mypy\fixup.py", line 262, in lookup_qualified_typeinfo
  File "mypy\fixup.py", line 290, in lookup_qualified
  File "mypy\fixup.py", line 299, in lookup_qualified_stnode
  File "mypy\lookup.py", line 47, in lookup_fully_qualified
AssertionError: Cannot find component 'namedtuple@326' for 'pyvisa.rname.namedtuple@326'
```

**Comment by jenshnielsen** [comment]
But it seems likely to be this issue https://github.com/python/mypy/issues/7281 or related

**Comment by MatthieuDartiailh** [comment]
Thanks for having another go at this @jenshnielsen. I will try to see if I can investigate on my side too.

@bilderbuchi regarding your question, testing using Keysight tooling has been introduced in #486. It relies on a Windows only software that Keysight makes available free of charge to PyVISA developers (for the development of projects under the PyVISA organization). They do not want to see it spread too widely (for intellectual property concerns) and since I am the only "active" member of the organization I am currently the only with access to it. The software behaves like a message based instrument and supports TCPIP, USB and GPIB, the last two requires two computers to operate and dedicated hardware. Looking at the testsuite under keysight_assisted_tests should give you an idea of how it works. I did not try but I doubt I could install it all from the command line on a CI, currently I run it manually on a computer in my lab and test only TCPIP. I uploaded the coverage manually after the run. In the future I hope to be able to have a two computers system behaving like a self-hosted CI and testing more hardware bus. This would in particular be extremely beneficial to pyvisa-py.

**Comment by bilderbuchi** [comment]
I see, great that they make this available! :-) So it's like a very (very) expanded version of pyvisa-sim?

**Comment by MatthieuDartiailh** [comment]
No because pyvisa-sim implements a fake Visa library whereas Keysight provides a fake instrument that is addressed through the conventional VISA library. This is why it can be used to validite pyvisa-py too.

**Comment by MatthieuDartiailh** [comment]
bors try

**Comment by MatthieuDartiailh** [comment]
@jenshnielsen I tried running mypy locally on qcodes with mypy master (05571b17 dated from 22/05) and I do not get the failure you reported (and I do get a typing error related to me changing the type of argument to flush).  Could you check again when mypy 0.780 get released ?

**Comment by MatthieuDartiailh** [comment]
@jenshnielsen I will likely merge tomorrow night. If you ever get a chance to test again let me know.

**Pull request merged**
