### PR TITLE
Enable Exceptions to be pickled/unpickled

### PR DESCRIPTION
**Pull request by bernizt**
Fixes a bug when trying to pickle/unpickle pyvisa exceptions. For example, previously it was not possible to send an exception instance from one process to another through a pipe.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Could you please add a test ? Once a test has been added I will try to merge quickly.

**Comment by bernizt** [comment]
Of course. I hope these new tests are enough.

**Comment by MatthieuDartiailh** [comment]
LGTM. At one point Github displayed an added file but it is gone now. @hgrecco @thliebig any comments ?
Otherwise I will merge in about a week. Thanks @bernizt

**Comment by bernizt** [comment]
I uploaded the file in a wrong directory so I had to amend it afterwards, so that is probably why an added file was shown for some minutes.

**Comment by MatthieuDartiailh** [comment]
Thanks @bernizt

**Pull request merged**
