### PR TITLE
Documentation re-organization and improvement

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
ping @gasparka I will try to rework a bit the docs here (but slowly) any input is welcome.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@hgrecco @tivek @gasparka any comments are welcome. The main changes are in rvalues and in communication that replaces the old tutorial.

**Comment by MatthieuDartiailh** [comment]
Ideally I would like to merge in a week or two, let me know if you need more time to look at it.

**Comment by gasparka** [comment]
Good work. 'Getting the instrument configuration right' will definitely save time for someone :)

**Pull request merged**
