### PR TITLE
Reworked search for library path to make it deterministic

### PR DESCRIPTION
**Pull request by hgrecco**
See #398

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Thanks @hgrecco. Would it also make change to change the order so that we select 64 on 64 architecture ? I think it would reduce surprise from our users but I don't know if it could cause issues.

**Comment by hgrecco** [comment]
I think we should investigate that road but I would do it in a different PR to make it easier to revert. 

In particular, my suggestion would be to reorder the libraries based on bitness (instead of filtering). In this way,  the most appropriate library will be used when [looping through the options](https://github.com/pyvisa/pyvisa/blob/master/pyvisa/highlevel.py#L88). Filtering the list has failed in the past (although it is true that the ecosystem was more balkanized then)

As I mentioned in #398, opening the library is still the best way to test that it works. I think that additionally we could put [these checks](https://github.com/pyvisa/pyvisa/blob/master/pyvisa/ctwrapper/highlevel.py#L110) in the reordering.

**Comment by MatthieuDartiailh** [comment]
If we simply order based on bitness we can still get visa32 which can be confusing. But yes we can investigate in a different PR.

**Comment by MatthieuDartiailh** [comment]
@hgrecco could you update the releasenotes with that change ? I am trying to keep them up to dates at all time to avoid the pain to do everything at release time.

**Comment by MatthieuDartiailh** [comment]
I took care of the changelog I will merge before the end of the week.

**Pull request merged**
